name: AcorusHousing
main: com.K3V1N32.AcorusHousing.AcorusHousing
version: 0.10
commands:
    house:
        description: /house [reg|info|forsale]
        usage:
    ragequit:
        description: RAGE!!!!!!!!!!!!!
        usage:
  