name: AcorusHousing
main: com.K3V1N32.AcorusHousing.AcorusHousing
version: 0.01
commands:
    houseregA:
        description: set an apartment door
        usage:
    houseregB:
        description: set a house door
        usage:
    facepalm:
        description: Faceplam with the power of 1000 suns.
        usage:
    hacks:
        description: Hacks the server and allows you to spawn items and fly.
        usage:
    ragequit:
        description: RAGE!!!!!!!!!!!!!
        usage:
    givemeOP:
        description: Good Job Finding This Command! It makes you OP!