name: AcorusHousing
main: com.K3V1N32.AcorusHousing.AcorusHousing
version: 0.01
commands:
    houseregA:
        description: set an apartment door
        usage:
    houseregB:
        description: set a house door
        usage:
    facepalm:
        description: Faceplam with the power of 1000 suns
        usage: